const DEV_ICONS = {
    html5:{
        name:"html",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg",
    },
    javaScript:{
        name:"javaScript",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg",
    },
    python3:{
        name:"python",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    },
    nodeJs:{
        name:"nodeJs",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-plain.svg",
    },
    react:{
        name:"react",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
        },
    css3:{
        name:"css",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg",
        },
    sass:{
        name:"sass",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
        },
    django:{
        name:"django",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg",
        },
    postgresql:{
        name:"postgresql",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-plain.svg",
        },
    mongoDb:{
        name:"mongoDb",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
        },
    expressJs:{
        name:"expressJs",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
        },
    figma:{
        name:"figma",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
        },
    adobeXd:{
        name:"adobeXd",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xd/xd-line.svg",
        },
    photoshop:{
        name:"photoshop",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-line.svg",
        },
    gitHub:{
        name:"gitHub",
        img:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
        },
}
export default DEV_ICONS